name:                blog-haskell
version:             0.1.0.0
github:              "githubuser/blog-haskell"
license:             BSD3
author:              "kugue99A"
maintainer:          "hisabisa99yohey@gmail.com"
copyright:           "2025 kugue99A"

extra-source-files:
- README.md

description:         HTTPリクエストに対して "hello world" を返すシンプルなサーバー

dependencies:
  - base
  - wai
  - warp
  - http-types
  - bytestring
  - case-insensitive
  - aeson
  - text
  - persistent
  - monad-logger
  - resource-pool
  - mtl
  - transformers
  - time

executables:
  blog-haskell-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N